// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBUdjvDH4xjwQu3oJLUqDVHPP7yb7U-I',
    appId: '1:733645855492:web:c31eda65bb70fbbddd8e51',
    messagingSenderId: '733645855492',
    projectId: 'example-a85c9',
    authDomain: 'example-a85c9.firebaseapp.com',
    storageBucket: 'example-a85c9.firebasestorage.app',
    measurementId: 'G-XY5RX1PPG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqU96gQlZGrz7Gv8QrnoqbBHCuhsh3TLU',
    appId: '1:733645855492:android:7f0538c399594067dd8e51',
    messagingSenderId: '733645855492',
    projectId: 'example-a85c9',
    storageBucket: 'example-a85c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCne6Y-yBW4ESYYIEyz6xfDSDkdM0cOlgs',
    appId: '1:733645855492:ios:669867af78b97708dd8e51',
    messagingSenderId: '733645855492',
    projectId: 'example-a85c9',
    storageBucket: 'example-a85c9.firebasestorage.app',
    iosBundleId: 'com.example.psychologicalTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCne6Y-yBW4ESYYIEyz6xfDSDkdM0cOlgs',
    appId: '1:733645855492:ios:669867af78b97708dd8e51',
    messagingSenderId: '733645855492',
    projectId: 'example-a85c9',
    storageBucket: 'example-a85c9.firebasestorage.app',
    iosBundleId: 'com.example.psychologicalTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmBUdjvDH4xjwQu3oJLUqDVHPP7yb7U-I',
    appId: '1:733645855492:web:b38b01dc7716ebd7dd8e51',
    messagingSenderId: '733645855492',
    projectId: 'example-a85c9',
    authDomain: 'example-a85c9.firebaseapp.com',
    storageBucket: 'example-a85c9.firebasestorage.app',
    measurementId: 'G-GPZQKY036Q',
  );
}
